/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/academica` | `/academica`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forca` | `/forca`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profissional` | `/profissional`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projetos` | `/projetos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sobre` | `/sobre`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/academica` | `/academica`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/forca` | `/forca`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profissional` | `/profissional`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/projetos` | `/projetos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sobre` | `/sobre`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/academica${`?${string}` | `#${string}` | ''}` | `/academica${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/forca${`?${string}` | `#${string}` | ''}` | `/forca${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profissional${`?${string}` | `#${string}` | ''}` | `/profissional${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/projetos${`?${string}` | `#${string}` | ''}` | `/projetos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sobre${`?${string}` | `#${string}` | ''}` | `/sobre${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/academica` | `/academica`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forca` | `/forca`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profissional` | `/profissional`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projetos` | `/projetos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sobre` | `/sobre`; params?: Router.UnknownInputParams; };
    }
  }
}
